"""
=========================================================
MarketVerse AI - Alert Engine
=========================================================
Handles Telegram, Email, Sound and Console Alerts.
=========================================================
"""

import smtplib
from email.mime.text import MIMEText
import requests


def send_telegram_alert(message, bot_token="", chat_id=""):
    """
    Send Telegram alert.
    """

    if not bot_token or not chat_id:
        return False

    url = f"https://api.telegram.org/bot{bot_token}/sendMessage"

    payload = {
        "chat_id": chat_id,
        "text": message
    }

    try:
        response = requests.post(url, json=payload, timeout=10)
        return response.status_code == 200
    except Exception:
        return False


def send_email_alert(
    subject,
    message,
    sender_email,
    sender_password,
    receiver_email,
    smtp_server="smtp.gmail.com",
    smtp_port=587
):
    """
    Send Email alert.
    """

    try:

        msg = MIMEText(message)

        msg["Subject"] = subject
        msg["From"] = sender_email
        msg["To"] = receiver_email

        server = smtplib.SMTP(smtp_server, smtp_port)

        server.starttls()

        server.login(sender_email, sender_password)

        server.sendmail(
            sender_email,
            receiver_email,
            msg.as_string()
        )

        server.quit()

        return True

    except Exception:
        return False


def play_sound():
    """
    Sound alert.
    """

    try:
        print("\a")
        return True
    except Exception:
        return False


def popup_alert(title, message):
    """
    Popup Alert.
    """

    print("=" * 60)
    print(title)
    print("-" * 60)
    print(message)
    print("=" * 60)


def generate_trade_alert(
    symbol,
    decision,
    confidence,
    price
):
    """
    Generate formatted alert message.
    """

    return (
        f"""
MarketVerse AI Alert

Symbol      : {symbol}
Signal      : {decision}
Confidence  : {confidence}%
Price       : {price}

Generated by MarketVerse AI
"""
    )


def send_all_alerts(
    symbol,
    decision,
    confidence,
    price,
    telegram=False,
    email=False,
    sound=True,
    bot_token=None,
    chat_id=None
):
    """
    Send all enabled alerts.
    """

    message = generate_trade_alert(
        symbol,
        decision,
        confidence,
        price
    )

    popup_alert("AI Trade Alert", message)

    if sound:
        play_sound()

    if telegram and bot_token and chat_id:
        send_telegram_alert(
        message,
        bot_token,
        chat_id
    )

    if email:
        print("Email alert enabled.")


if __name__ == "__main__":

    send_all_alerts(
        symbol="RELIANCE",
        decision="BUY",
        confidence=86,
        price=2985.45
    )
