"""
MarketVerse AI
Shared Market Context

Purpose
-------
CentralBrain uses this object as the single shared
context for the complete intelligence pipeline.

Every analysis module writes its evidence into this
context.

The context itself NEVER performs analysis,
prediction, strategy generation, or decision making.

Author : MarketVerse AI
Version : 1.0
"""


class MarketContext:
    """
    Shared Market Context

    Stores every analysis result generated by
    the intelligence pipeline.
    """

    def __init__(self, symbol=None):

        self.data = {

            # Basic Information
            "symbol": symbol,

            # Raw Market Data
            "market_data": {},

            # Scanner
            "scanner": {},

            # AI
            "ai": {},

            # News
            "news": {},

            # News Analysis
            "news_analysis": {},

            # Market Events
            "events": {},

            # Technical Analysis
            "technical": {},

            # Pattern Analysis
            "pattern": {},

            # Volume Analysis
            "volume": {},

            # Sentiment
            "sentiment": {},

            # Prediction
            "prediction": {},

            # Strategy
            "strategy": {},

            # Risk
            "risk": {},

            # Final Decision
            "decision": {},

            # Future Intelligence
            "confidence": {},
            "probability": {},
            "opportunity": {},

            # Metadata
            "metadata": {}
        }

    def get(self):
        """Return complete market context."""
        return self.data

    def update(self, key, value):
        """Update one section of the context."""
        self.data[key] = value

    def read(self, key, default=None):
        """Read one section from the context."""
        return self.data.get(key, default)
