"""
=========================================================
MarketVerse AI
Strategy Engine
=========================================================

Purpose
-------
Combines evidence generated by the MarketVerse
intelligence pipeline and produces a strategy proposal.

This module does NOT make the final market decision.

CentralBrain:
    Orchestrates the complete pipeline.

DecisionCore:
    Produces the final decision.

Strategy Engine:
    Generates a strategy recommendation based on
    available market intelligence.
=========================================================
"""


# =========================================================
# STRATEGY CALCULATION
# =========================================================

def calculate_strategy(
    market,
    technical,
    prediction,
    sentiment=None
):
    """
    Professional Strategy Engine

    Combines:

    - Market Evidence
    - Technical Analysis
    - AI Prediction
    - Sentiment

    Returns strategy evidence only.
    """

    score = 0
    reasons = []

    # =====================================================
    # AI / Prediction Evidence
    # =====================================================

    prediction = prediction or {}

    confidence = prediction.get(
        "confidence",
        50
    )

    signal = prediction.get(
        "signal",
        "HOLD"
    )

    if signal == "STRONG BUY":

        score += 40

        reasons.append(
            "Prediction engine indicates strong bullish movement"
        )

    elif signal == "BUY":

        score += 30

        reasons.append(
            "Prediction engine indicates bullish movement"
        )

    elif signal == "STRONG SELL":

        score -= 40

        reasons.append(
            "Prediction engine indicates strong bearish movement"
        )

    elif signal == "SELL":

        score -= 30

        reasons.append(
            "Prediction engine indicates bearish movement"
        )

    # =====================================================
    # Technical Evidence
    # =====================================================

    technical = technical or {}

    ema20 = technical.get(
        "ema20",
        0
    )

    ema50 = technical.get(
        "ema50",
        0
    )

    macd = technical.get(
        "macd",
        0
    )

    macd_signal = technical.get(
        "macd_signal",
        0
    )

    rsi = technical.get(
        "rsi",
        50
    )

    # -----------------------------------------------------
    # EMA Trend
    # -----------------------------------------------------

    if (
        ema20
        and ema50
        and ema20 > ema50
    ):

        score += 20

        reasons.append(
            "EMA trend structure is bullish"
        )

    elif (
        ema20
        and ema50
        and ema20 < ema50
    ):

        score -= 20

        reasons.append(
            "EMA trend structure is bearish"
        )

    # -----------------------------------------------------
    # MACD
    # -----------------------------------------------------

    if (
        macd is not None
        and macd_signal is not None
    ):

        if macd > macd_signal:

            score += 10

            reasons.append(
                "MACD momentum is bullish"
            )

        elif macd < macd_signal:

            score -= 10

            reasons.append(
                "MACD momentum is bearish"
            )

    # -----------------------------------------------------
    # RSI
    # -----------------------------------------------------

    if rsi < 30:

        score += 5

        reasons.append(
            "RSI indicates oversold conditions"
        )

    elif rsi > 70:

        score -= 5

        reasons.append(
            "RSI indicates overbought conditions"
        )

    # =====================================================
    # Market Evidence
    # =====================================================

    market = market or {}

    change = market.get(
        "change_percent",
        0
    )

    if change > 0:

        score += 10

        reasons.append(
            "Market price movement is positive"
        )

    elif change < 0:

        score -= 10

        reasons.append(
            "Market price movement is negative"
        )

    # =====================================================
    # Sentiment Evidence
    # =====================================================

    sentiment_score = None
    sentiment_label = None

    if sentiment:

        sentiment_score = sentiment.get(
            "score"
        )

        sentiment_label = sentiment.get(
            "sentiment"
        )

    # Numeric sentiment score

    if sentiment_score is not None:

        if sentiment_score > 70:

            score += 10

            reasons.append(
                "Market sentiment is strongly positive"
            )

        elif sentiment_score < 30:

            score -= 10

            reasons.append(
                "Market sentiment is strongly negative"
            )

    # Text sentiment compatibility

    elif sentiment_label:

        sentiment_label = str(
            sentiment_label
        ).upper()

        if sentiment_label in (
            "POSITIVE",
            "BULLISH",
            "VERY BULLISH"
        ):

            score += 10

            reasons.append(
                "Market sentiment is bullish"
            )

        elif sentiment_label in (
            "NEGATIVE",
            "BEARISH",
            "VERY BEARISH"
        ):

            score -= 10

            reasons.append(
                "Market sentiment is bearish"
            )

    # =====================================================
    # Strategy Classification
    # =====================================================

    if score >= 60:

        decision = "STRONG BUY"

        action = "BUY"

        strength = "STRONG"

    elif score >= 30:

        decision = "BUY"

        action = "BUY"

        strength = "NORMAL"

    elif score <= -60:

        decision = "STRONG SELL"

        action = "SELL"

        strength = "STRONG"

    elif score <= -30:

        decision = "SELL"

        action = "SELL"

        strength = "NORMAL"

    else:

        decision = "HOLD"

        action = "HOLD"

        strength = "NEUTRAL"

    # =====================================================
    # Strategy Confidence
    # =====================================================

    strategy_confidence = min(
        max(
            abs(score) + 40,
            0
        ),
        95
    )

    # Prediction confidence is evidence,
    # not the complete strategy confidence.

    if confidence:

        strategy_confidence = round(
            (
                strategy_confidence
                + float(confidence)
            ) / 2,
            2
        )

    # =====================================================
    # Default Reason
    # =====================================================

    if not reasons:

        reasons.append(
            "Insufficient directional evidence"
        )

    # =====================================================
    # Return Strategy Evidence
    # =====================================================

    return {

        "status": "success",

        "action": action,

        "strength": strength,

        "decision": decision,

        "score": score,

        "confidence": strategy_confidence,

        "reasons": reasons

    }


# =========================================================
# CENTRAL BRAIN COMPATIBILITY
# =========================================================

def generate_strategy(
    analysis,
    sentiment=None,
    prediction=None
):
    """
    CentralBrain Strategy Interface.

    Supports two calling styles.

    -----------------------------------------------------

    CentralBrain:

        generate_strategy(result)

    -----------------------------------------------------

    Legacy compatibility:

        generate_strategy(
            technical,
            sentiment,
            prediction
        )

    -----------------------------------------------------
    """

    # =====================================================
    # CENTRAL BRAIN MODE
    # =====================================================

    if (
        isinstance(analysis, dict)
        and (
            "technical" in analysis
            or "prediction" in analysis
            or "sentiment" in analysis
        )
    ):

        technical = analysis.get(
            "technical",
            {}
        )

        prediction_data = analysis.get(
            "prediction",
            {}
        )

        sentiment_data = analysis.get(
            "sentiment",
            analysis.get(
                "news_analysis",
                {}
            )
        )

        # -------------------------------------------------
        # Market Data Resolution
        # -------------------------------------------------

        market = analysis.get(
            "market",
            {}
        )

        # Technical module contains price information.

        if not market:

            market = {

                "price": technical.get(
                    "price",
                    0
                ),

                "change_percent": technical.get(
                    "change_percent",
                    0
                )

            }

        return calculate_strategy(

            market=market,

            technical=technical,

            prediction=prediction_data,

            sentiment=sentiment_data

        )

    # =====================================================
    # LEGACY COMPATIBILITY MODE
    # =====================================================

    technical = analysis or {}

    sentiment_data = sentiment or {}

    prediction_data = prediction or {}

    return calculate_strategy(

        market={},

        technical=technical,

        prediction=prediction_data,

        sentiment=sentiment_data

    )
